---
title: Заметки по американски
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
header_title: Блог
email: qwertyaseo@yandex.ru
author: Артурчик
description: Изучение английского языка
baseurl: https://moccaz.github.io
url: https://moccaz.github.io
date_format: "%-d.%m.%Y"
google_analytics: ''
google_verification: ''
facebook_app_id: ''
animated: false
show_related_posts: false
show_post_footer: true
show_social_icons: true
ajaxify_contact_form: true
disqus_shortname: disqus_xxx
github_username: 
bitbucket_username: 
stackoverflow_id: 
twitter_username: 
google_plus_id: 
linkedin_username: 
facebook_username: 
angellist_username: 
medium_id: 
bitcoin_url: 
paypal_url: 
flattr_button: 
instagram_username: 
show_sharing_icons: true
share_text: Поделись
share_facebook: true
share_twitter: true
share_googleplus: false
share_linkedin: false
share_digg: false
share_tumblr: false
share_reddit: false
share_stumbleupon: false
share_hackernews: false
markdown: kramdown
redcarpet:
  extensions:
  - smart
  - tables
  - with_toc_data
permalink: "/:title/"
paginate: 15
sass:
  compressed: true
gems:
- jekyll-paginate
